targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/src/interfaces/**.dart
    builders:
      mockito|mockBuilder:
        generate_for:
          - lib/src/interfaces/**.dart
